# =============================================================================
# Adapted from MedAgent-Pro (https://github.com/jinlab-imvr/MedAgent-Pro)
# Original work: Wang et al., "MedAgent-Pro: Towards Evidence-Based
#   Multi-Modal Medical Diagnosis via Reasoning Agentic Workflow",
#   ICLR 2026.
# Upstream license: no license file. Used with attribution; see
#   baselines/MedAgent-Pro/ATTRIBUTION.md for details.
# Modifications by the DermAgent authors for dermatology benchmarks.
# =============================================================================

"""
Case-level execution for dermatology benchmarks (Task 1-3).

Loads a plan.json generated by Derm_Task_level.py, then for each sample in
the CSV dataset:
  1. Runs quantitative steps (PanDerm, MAKE, RAG via bridge tools).
  2. Runs qualitative steps (GPT-4o VLM analysis via GPT_Decider).
  3. Summarises qualitative results (Summary_Module).
  4. Produces a final decision (task-specific Decider).

Usage:
    # Task 1: Zero-shot classification (HAM10000)
    python Derm_Case_level.py --task 1 \\
        --csv-path ../../datasets/ham10000/HAM10000_benchmark_500.csv \\
        --image-dir ../../datasets/ham10000 \\
        --max-samples 500

    # Task 2: Concept annotation (Derm7pt-100)
    python Derm_Case_level.py --task 2 \\
        --csv-path ../../datasets/derm7pt/meta_task2_sample_100.csv \\
        --image-dir ../../datasets/derm7pt/final_images \\
        --max-samples 100

    # Task 3: Image captioning (SkinCAP-100)
    python Derm_Case_level.py --task 3 \\
        --csv-path ../../datasets/skin_cap/skin_cap_meta_100.csv \\
        --image-dir ../../datasets/skin_cap \\
        --max-samples 100
"""

import argparse
import json
import os
import sys
import time
import traceback
from datetime import datetime
from pathlib import Path

import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv

load_dotenv()

# MedAgent-Pro modules
from CodingAgent import Coding_Agent
from Decider import GPT_Decider, Pro_Decider, MultiClass_Decider
from Summary_Module import Summary_Module
from utils import (
    ensure_pkg_inited,
    register_generated_function,
    command_to_fn_name,
    snake,
    inputs_desc,
    read_prev_output,
    build_qual_prompt,
)

# DermAgent bridge tools
from Dermatology.tools import panderm_classify, make_annotate, rag_retrieve

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

HAM10000_CLASSES = [
    "melanocytic nevi", "melanoma", "basal cell carcinoma",
    "actinic keratosis", "benign keratosis", "dermatofibroma",
    "vascular lesion",
]

# Task 2 concept columns (Derm7pt)
DERM7PT_CONCEPTS = [
    "pigment_network",
    "blue_whitish_veil",
    "vascular_structures",
    "pigmentation",
    "streaks",
    "dots_and_globules",
    "regression_structures",
]

# =============================================================================
# Task-specific defaults
# =============================================================================
TASK_DEFAULTS = {
    1: {
        "data_root": "Dermatology/task1_diagnosis",
        "image_col": "filename",
        "label_col": "diag",
    },
    2: {
        "data_root": "Dermatology/task2_concept",
        "image_col": "ImageID",
        "label_col": None,
    },
    3: {
        "data_root": "Dermatology/task3_captioning",
        "image_col": "filename",
        "label_col": "caption_zh_polish_en",
    },
}


def parse_args():
    p = argparse.ArgumentParser(
        description="Run MedAgent-Pro case-level execution on dermatology tasks"
    )
    p.add_argument("--task", type=int, required=True, choices=[1, 2, 3])
    p.add_argument("--csv-path", type=str, required=True)
    p.add_argument("--image-dir", type=str, required=True)
    p.add_argument("--image-col", type=str, default=None,
                    help="CSV column for image filename (auto-detected per task)")
    p.add_argument("--max-samples", type=int, default=None)
    p.add_argument("--resume", action="store_true",
                    help="Skip samples whose record dir already has final_diagnosis.json")
    p.add_argument("--output-tag", type=str, default=None,
                    help="Subdirectory tag under record/ (default: timestamp)")
    return p.parse_args()


# =============================================================================
# Core execution loop (shared across tasks)
# =============================================================================

def run_plan_for_sample(
    plan: list,
    plan_by_id: dict,
    tool_by_id: dict,
    tool_registry: dict,
    image_path: str,
    save_dir: str,
    task: dict,
    analyzer: GPT_Decider,
    summarizer: Summary_Module,
    task_id: int,
):
    """Execute all plan steps for a single sample."""
    for step in plan:
        at = str(step.get("action_type", "")).lower()
        tool_ids = step.get("tool", []) or []
        if not isinstance(tool_ids, list):
            tool_ids = [tool_ids]
        save_name = step.get("output_path", "diagnosis.json")

        if at == "quantitative":
            _run_quantitative(
                step, tool_ids, tool_by_id, tool_registry, plan_by_id,
                image_path, save_dir, save_name, task
            )
        elif at == "qualitative":
            _run_qualitative(
                step, plan_by_id, image_path, save_dir, save_name,
                analyzer, summarizer, task_id
            )


def _run_quantitative(step, tool_ids, tool_by_id, tool_registry, plan_by_id,
                       image_path, save_dir, save_name, task):
    for tid in tool_ids:
        tool_def = tool_by_id.get(int(tid))
        if tool_def is None:
            print(f"  [warn] tool id {tid} not in toolset")
            continue

        if "coding" in str(tool_def.get("type", "")).lower():
            fn_name = (
                f"{snake(step.get('action') or step.get('output_type') or 'generated_fn')}"
                f"_{int(step.get('id', 0))}"
            )
        else:
            fn_name = command_to_fn_name(tool_def.get("command", ""))

        fn = tool_registry.get(fn_name)
        if fn is None:
            print(f"  [warn] function '{fn_name}' not registered")
            continue

        deps = step.get("input_type", []) or []
        resolved = []
        for dep in deps:
            dep = int(dep)
            if dep == 0:
                resolved.append(image_path)
            else:
                prev = plan_by_id.get(dep)
                if prev:
                    resolved.append(os.path.join(save_dir, prev.get("output_path", "")))

        try:
            if "coding" in str(tool_def.get("type", "")).lower():
                fn(resolved, save_dir, save_name)
            else:
                primary = resolved[0] if resolved else image_path
                fn(primary, save_dir, save_name)
        except Exception as e:
            print(f"  [error] '{fn_name}': {e}")


def _run_qualitative(step, plan_by_id, image_path, save_dir, save_name,
                      analyzer, summarizer, task_id):
    try:
        image_input, text_input = [], []
        for dep in step.get("input_type", []) or []:
            dep = int(dep)
            if dep == 0:
                image_input.append(image_path)
            else:
                prev_step = plan_by_id.get(dep, {})
                prev_save_name = prev_step.get("output_path", "")
                t, img = read_prev_output(save_dir, prev_save_name, dep)
                if img:
                    image_input.append(img)
                if t:
                    text_input.append(t)

        ques = step.get("action", "")
        full_prompt = build_qual_prompt(ques, text_input)
        step_field = f"step_{step.get('id')}"

        analyzer.decide(
            output_file=os.path.join(save_dir, save_name),
            prompt=full_prompt,
            image_paths=image_input,
            field=step_field,
        )

        # Summary prompt adapts per task
        if task_id == 1:
            summary_prompt = (
                f"Based on the above analysis, what is the most likely diagnosis? "
                f"The task is: {ques}. "
                f"Answer with ONLY the disease name from: {', '.join(HAM10000_CLASSES)}"
            )
        elif task_id == 2:
            summary_prompt = (
                f"Based on the above text, does this image show the described feature? "
                f"The task is: {ques}. Answer with only one word (Yes or No)"
            )
        else:  # task 3 — no summary, raw VLM output is the caption
            return

        summarizer.summarize(
            input_file=os.path.join(save_dir, save_name),
            output_file=os.path.join(save_dir, "brief_diagnosis.json"),
            prompt=summary_prompt,
            field=step_field,
        )
    except Exception as e:
        print(f"  [error] qualitative step {step.get('id')}: {e}")


# =============================================================================
# Task-specific final decision
# =============================================================================

def final_decision_task1(plan, save_dir, task, image_path, decider):
    """Multi-class classification → pick one of HAM10000_CLASSES."""
    indicators = _collect_indicators(plan, save_dir)
    input_desc = str(task.get("input", ""))
    disease_goal = str(task.get("disease", ""))

    prompt = (
        f"You are a clinical decision assistant for dermatology.\n"
        f"Input: {input_desc}\n"
        f"Goal: {disease_goal}\n"
    )
    decider.decide(
        output_file=os.path.join(save_dir, "final_diagnosis.json"),
        prompt=prompt,
        indicators=indicators,
        candidate_classes=HAM10000_CLASSES,
        image_paths=[image_path],
        field="overall",
    )


def final_decision_task2(plan, save_dir):
    """Concept annotation — collect per-concept Yes/No from brief_diagnosis.json."""
    brief_path = os.path.join(save_dir, "brief_diagnosis.json")
    if not os.path.exists(brief_path):
        return

    with open(brief_path, "r", encoding="utf-8") as f:
        brief = json.load(f)

    concepts_result = {}
    for step in plan:
        if str(step.get("output_type", "")).lower() != "final indicator":
            continue
        action = step.get("action", "").lower()
        step_field = f"step_{step.get('id')}"
        answer = str(brief.get(step_field, "")).strip().lower()
        is_present = "yes" in answer
        concepts_result[step.get("action", "")] = {
            "present": is_present,
            "raw_answer": brief.get(step_field, ""),
        }

    out_path = os.path.join(save_dir, "final_diagnosis.json")
    result = {"overall": {"concepts": concepts_result}}
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=4, ensure_ascii=False)


def final_decision_task3(plan, save_dir):
    """Captioning — extract the last qualitative VLM step's output as caption."""
    diag_path = os.path.join(save_dir, "diagnosis.json")
    if not os.path.exists(diag_path):
        return

    with open(diag_path, "r", encoding="utf-8") as f:
        diag = json.load(f)

    # Find the last qualitative step (highest id with action_type=qualitative)
    last_qual = None
    for step in reversed(plan):
        if str(step.get("action_type", "")).lower() == "qualitative":
            last_qual = step
            break

    caption = ""
    if last_qual:
        step_field = f"step_{last_qual.get('id')}"
        caption = str(diag.get(step_field, "")).strip()

    if not caption:
        # Fallback: take the last available step output
        for key in sorted(diag.keys(), reverse=True):
            if diag[key]:
                caption = str(diag[key]).strip()
                break

    out_path = os.path.join(save_dir, "final_diagnosis.json")
    result = {"overall": {"caption": caption}}
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=4, ensure_ascii=False)


def _collect_indicators(plan, save_dir):
    """Gather indicator evidence from brief_diagnosis.json for Pro/MultiClass_Decider."""
    brief_path = os.path.join(save_dir, "brief_diagnosis.json")
    if os.path.exists(brief_path):
        with open(brief_path, "r", encoding="utf-8") as f:
            brief = json.load(f)
    else:
        brief = {}

    diag_path = os.path.join(save_dir, "diagnosis.json")
    if os.path.exists(diag_path):
        with open(diag_path, "r", encoding="utf-8") as f:
            diag = json.load(f)
    else:
        diag = {}

    indicators = []
    for step in plan:
        step_field = f"step_{step.get('id')}"
        at = str(step.get("action_type", "")).lower()
        ot = str(step.get("output_type", "")).lower()

        evidence = brief.get(step_field, diag.get(step_field, ""))
        if isinstance(evidence, (dict, list)):
            evidence = json.dumps(evidence, ensure_ascii=False)[:500]

        indicators.append({
            "indicator_name": step.get("action", f"step_{step.get('id')}"),
            "evidence": str(evidence),
            "action_type": at,
            "output_type": ot,
        })
    return indicators


# =============================================================================
# Main
# =============================================================================

def main():
    args = parse_args()
    task_id = args.task
    defaults = TASK_DEFAULTS[task_id]
    data_root = defaults["data_root"]

    image_col = args.image_col or defaults["image_col"]
    image_dir = args.image_dir

    # Load task + plan + toolset
    with open(os.path.join(data_root, "task.json"), "r") as f:
        task = json.load(f)
    plan_path = os.path.join(data_root, "plan.json")
    if not os.path.exists(plan_path):
        print(f"[ERROR] {plan_path} not found. Run Derm_Task_level.py first.")
        sys.exit(1)
    with open(plan_path, "r") as f:
        plan = json.load(f)
    with open(os.path.join(data_root, "toolset.json"), "r") as f:
        toolset = json.load(f)

    tool_by_id = {int(t["id"]): t for t in toolset if "id" in t}
    plan_by_id = {int(s["id"]): s for s in plan if "id" in s}

    # Tool function registry
    TOOL_FN_REGISTRY = {
        "panderm_classify": panderm_classify,
        "make_annotate": make_annotate,
        "rag_retrieve": rag_retrieve,
    }

    # Code generation for coding steps
    ensure_pkg_inited(data_root)
    coder = Coding_Agent(OPENAI_API_KEY)
    code_path = os.path.join(data_root, "tools", "GenCode.py")
    os.makedirs(os.path.dirname(code_path), exist_ok=True)
    if not os.path.exists(code_path):
        with open(code_path, "w", encoding="utf-8") as f:
            f.write("# Generated code\n")

    for step in plan:
        step_tool_ids = step.get("tool", []) or []
        if not isinstance(step_tool_ids, list):
            step_tool_ids = [step_tool_ids]
        is_coding = any(
            "coding" in str(tool_by_id.get(int(tid), {}).get("type", "")).lower()
            for tid in step_tool_ids
        )
        if not is_coding:
            continue

        fn_name, requirement = _build_requirement(step, plan_by_id, tool_by_id, task)
        try:
            coder.generate_function(
                output_file=code_path,
                requirement=requirement,
                enforce_function_name=fn_name,
                extra_context=(
                    "`inputs` is a list; each item may be a file path or an "
                    "in-memory object. Handle both gracefully."
                ),
                model="gpt-4o",
            )
            register_generated_function(data_root, TOOL_FN_REGISTRY, fn_name)
        except Exception as e:
            print(f"[warn] CodingAgent failed for step {step.get('id')}: {e}")

    # LLM modules
    analyzer = GPT_Decider(OPENAI_API_KEY)
    summarizer = Summary_Module(OPENAI_API_KEY)
    mc_decider = MultiClass_Decider(OPENAI_API_KEY) if task_id == 1 else None

    # Load dataset
    df = pd.read_csv(args.csv_path)
    if args.max_samples:
        df = df.head(args.max_samples)

    # Output directory
    tag = args.output_tag or datetime.now().strftime("%Y%m%d_%H%M%S")
    record_root = os.path.join(data_root, "record", tag)
    os.makedirs(record_root, exist_ok=True)

    # Save run config
    run_config = {
        "task": task_id,
        "csv_path": args.csv_path,
        "image_dir": image_dir,
        "num_samples": len(df),
        "timestamp": tag,
        "plan_steps": len(plan),
    }
    with open(os.path.join(record_root, "run_config.json"), "w") as f:
        json.dump(run_config, f, indent=2)

    print(f"\nTask {task_id} | {len(df)} samples | {len(plan)} plan steps")
    print(f"Output: {record_root}\n")

    # Main execution loop
    results = []
    for idx, row in tqdm(df.iterrows(), total=len(df), desc=f"Task {task_id}"):
        img_file = str(row[image_col])
        image_path = os.path.join(image_dir, img_file)
        if not os.path.exists(image_path):
            print(f"  [skip] image not found: {image_path}")
            continue

        sample_id = Path(img_file).stem
        save_dir = os.path.join(record_root, sample_id)

        # Resume: skip already-completed samples
        if args.resume and os.path.exists(os.path.join(save_dir, "final_diagnosis.json")):
            continue

        os.makedirs(save_dir, exist_ok=True)

        t0 = time.time()
        try:
            # Run all plan steps
            run_plan_for_sample(
                plan, plan_by_id, tool_by_id, TOOL_FN_REGISTRY,
                image_path, save_dir, task, analyzer, summarizer, task_id
            )

            # Final decision (task-specific)
            if task_id == 1:
                final_decision_task1(plan, save_dir, task, image_path, mc_decider)
            elif task_id == 2:
                final_decision_task2(plan, save_dir)
            elif task_id == 3:
                final_decision_task3(plan, save_dir)

            elapsed = time.time() - t0
            results.append({"sample": sample_id, "status": "ok", "time": elapsed})

        except Exception as e:
            elapsed = time.time() - t0
            print(f"  [FAIL] {sample_id}: {e}")
            traceback.print_exc()
            results.append({"sample": sample_id, "status": "error", "error": str(e),
                            "time": elapsed})

    # Save execution summary
    summary_path = os.path.join(record_root, "execution_summary.json")
    ok = sum(1 for r in results if r["status"] == "ok")
    err = sum(1 for r in results if r["status"] == "error")
    with open(summary_path, "w") as f:
        json.dump({
            "total": len(results), "ok": ok, "error": err,
            "results": results,
        }, f, indent=2)

    print(f"\nDone: {ok}/{len(results)} succeeded, {err} errors")
    print(f"Results: {record_root}")
    print(f"Next: python Derm_Evaluator.py --task {task_id} --record-dir {record_root} "
          f"--csv-path {args.csv_path}")


def _build_requirement(step, plan_by_id, tool_by_id, task):
    """Build (function_name, requirement_text) for Coding_Agent."""
    base = step.get("action") or step.get("output_type") or "generated_fn"
    fn_name = f"{snake(base)}_{int(step.get('id', 0))}"
    in_desc_list = inputs_desc(step, plan_by_id, tool_by_id, task.get("input", ""))
    in_desc_str = ", ".join(in_desc_list)
    out_desc = str(step.get("output_type", "")).strip()
    step_id = int(step.get("id", 0))

    requirement = (
        "Implement a Python function with the EXACT signature:\n"
        f"{fn_name}(inputs, save_dir, save_name)\n\n"
        "Semantics:\n"
        "- `inputs` is a LIST; elements correspond IN ORDER to step dependencies.\n"
        f"- Conceptual inputs: {in_desc_str}\n"
        f"- Output (conceptual): {out_desc}\n\n"
        "Constraints:\n"
        "- Self-contained (import inside if needed). No print statements.\n"
        "- Always use `os.path.join(save_dir, save_name)` as the output path for non-image results.\n"
        "- When writing non-image results, read existing JSON if present, "
        f"update key 'step_{step_id}', write back with ensure_ascii=False.\n"
        "- Add a brief docstring.\n"
    )
    return fn_name, requirement


if __name__ == "__main__":
    main()
